# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            bethbrains
tagline:          'Salesforce MVP and General Nerd'
description:      'No, my last name isn''t actually Brains.'
url:              http://bethbrains.github.io
baseurl:          /

author:
  name:           'Beth Breisnes'
  url:            https://twitter.com/bethbrains

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
